volumes:
  postgres-data:
    external: true

services:
  fastapi:
    build:
      context: api
      dockerfile: Dockerfile.dev
    environment:
      - CORS_HOST=http://localhost:5173
      - DATABASE_URL=postgresql://example_user:secret@db/example
      - SIGNING_KEY=${SIGNING_KEY}
      - PEXELS_API_KEY = "QEDELBUOXiIWk9okf7M5Lc1Asy1QwHVFM0qvVtmMtv1MXTVStdzx66eC"
    ports:
      - "8000:8000"
    user: "1000:1000" # on macOS and Linux, replace this with your real user id and group id
    volumes:
      - ./api:/app

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    user: "1000:1000" # on macOS and Linux, replace this with your real user id and group id
    volumes:
      - ./ghi:/app
    environment:
      - VITE_API_HOST=http://localhost:8000
    ports:
      - "5173:5173"

  db:
    image: postgres:14.5-bullseye
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=example_user
      - POSTGRES_DB=example
    ports:
      - "15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
